from aiogram.dispatcher.filters.state import State, StatesGroup
class Register(StatesGroup):
    first_name = State()
    last_name = State()
    #email = State()
    #phone_number = State()
    dasturlash_tili = State()
    phone_number = State()
    Hudud = State()
    cash = State()
    yosh = State()
    kasb = State()
    vaqt = State()
    maqsad = State()
    admin = State()
    idora = State()
    ish = State()
    qosh = State()
    masul = State()